// Requires Playwright with Chromium. Run against `pnpm dev`: node scripts/check-ui.mjs.
import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
const { chromium } = createRequire(import.meta.url)('playwright')
const browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_BROWSER_CHANNEL ? { channel: process.env.PLAYWRIGHT_BROWSER_CHANNEL } : {}) })
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } })
const base = process.env.DESKTOP_TEST_URL ?? 'http://127.0.0.1:1421'
const failures = []
page.on('pageerror', e => failures.push(e.message))
const check = async (name, fn) => { await fn(); console.log(`PASS ${name}`) }
const expectText = async (selector, text) => page.waitForFunction(([s, t]) => document.querySelector(s)?.textContent?.includes(t), [selector, text])
try {
  await check('desktop hover menus survive live download updates and retain selection', async () => {
    const nav = await browser.newPage()
    nav.on('pageerror', e => failures.push(e.message))
    await nav.goto(`${base}/test/nav.html`)
    const library = nav.getByRole('button', { name: 'library', exact: true })
    await library.hover()
    const item = nav.getByRole('menuitem', { name: 'Downloads', exact: true })
    await item.waitFor(); await item.hover(); await item.focus()
    for (let i = 1; i <= 30; i++) {
      await nav.evaluate(() => window.navFixture.tick())
      await nav.waitForFunction(n => document.querySelector('#progress')?.textContent === String(n), i)
      assert.equal(await library.getAttribute('aria-expanded'), 'true')
      assert.equal(await nav.evaluate(() => document.activeElement?.textContent), 'Downloads')
      await nav.waitForTimeout(50)
    }
    assert.equal(await nav.evaluate(() => window.navFixture.calls.filter(c => c.startsWith('menu_')).length), 0)
    await nav.keyboard.press('Enter')
    assert.equal(await nav.evaluate(() => window.navFixture.selected()), 30)
    await library.focus(); await nav.keyboard.press('ArrowDown')
    await item.waitFor(); await nav.keyboard.press('Escape')
    assert.equal(await nav.getByRole('menu').count(), 0)
    assert.equal(await nav.evaluate(() => document.activeElement?.textContent), 'library')
    await library.hover(); await item.waitFor(); await nav.locator('#progress').hover()
    await nav.waitForFunction(() => !document.querySelector('[role="menu"]'))
    await nav.getByRole('button', { name: 'store', exact: true }).click()
    await library.hover()
    await nav.waitForFunction(() => window.navFixture.calls.includes('menu_open'))
    assert.equal(await nav.getByRole('menu').count(), 0)
    await nav.locator('#local').click()
    await library.hover(); await item.waitFor()
    assert(await nav.evaluate(() => window.navFixture.calls.includes('menu_close')))
    await nav.close()
  })
  await page.goto(`${base}/test/ui.html`)
  await check('loading is distinct from an empty download list', async () => {
    await expectText('#downloads', 'Loading downloads')
    assert(!await page.locator('#downloads').innerText().then(t => t.includes('No downloads')))
    await page.evaluate(() => window.fixture.reject('downloads_list'))
    await expectText('#downloads', 'Downloads unavailable')
    await page.locator('#downloads').getByRole('button', { name: 'Retry', exact: true }).click()
    await expectText('#downloads', 'Loading downloads')
    await page.evaluate(() => window.fixture.resolve('downloads_list', []))
    await expectText('#downloads', 'No downloads')
  })
  await check('quick-exit explanation survives a successful refresh', async () => {
    await page.evaluate(() => window.fixture.resolve('library_list', []))
    await page.evaluate(() => window.fixture.emit('game-state', { id: 'fixture', running: false, seconds: 1, code: 0 }))
    await expectText('#library-error', 'closed again')
    await page.evaluate(() => window.fixture.resolve('library_list', []))
    await expectText('#library-error', 'closed again')
  })
  await check('a stale library response cannot replace the latest one', async () => {
    await page.locator('#reload-library').click(); await page.locator('#reload-library').click()
    await page.evaluate(() => window.fixture.resolve('library_list', [{ ...window.fixture.game, title: 'Newest' }], true))
    await expectText('#library-games', 'Newest')
    await page.evaluate(() => window.fixture.resolve('library_list', [{ ...window.fixture.game, title: 'Stale' }]))
    assert.equal(await page.locator('#library-games').textContent(), 'Newest')
  })
  await check('dialogs isolate the background, wrap focus, and restore the trigger', async () => {
    await page.locator('#open').click()
    assert(await page.locator('#root').evaluate(el => el.inert))
    await page.locator('#last').focus(); await page.keyboard.press('Tab')
    assert.equal(await page.evaluate(() => document.activeElement?.getAttribute('aria-label')), 'Close')
    await page.keyboard.press('Shift+Tab')
    assert.equal(await page.evaluate(() => document.activeElement?.id), 'last')
    await page.locator('#nested').click()
    await page.locator('#nested-last').focus(); await page.keyboard.press('Tab')
    assert(await page.getByRole('dialog', { name: 'Nested fixture', exact: true }).evaluate(el => el.contains(document.activeElement)))
    await page.keyboard.press('Escape')
    assert.equal(await page.evaluate(() => document.activeElement?.id), 'nested')
    await page.keyboard.press('Escape')
    assert.equal(await page.evaluate(() => document.activeElement?.id), 'open')
    assert(!await page.locator('#root').evaluate(el => el.inert))
  })
  await check('choice and menu keyboard behavior', async () => {
    await page.locator('#open').click()
    await page.getByRole('radio', { name: 'Alpha', exact: true }).focus()
    await page.keyboard.press('ArrowRight')
    assert.equal(await page.getByRole('radio', { name: 'Beta', exact: true }).getAttribute('aria-checked'), 'true')
    assert.equal(await page.getByRole('radio', { name: 'Alpha', exact: true }).getAttribute('tabindex'), '-1')
    const dropdown = page.getByRole('button', { name: 'Fixture dropdown', exact: true })
    await dropdown.focus(); await page.keyboard.press('ArrowDown')
    assert.equal(await page.evaluate(() => document.activeElement?.textContent?.trim()), 'Beta')
    await page.keyboard.press('Home'); await page.keyboard.press('Enter')
    assert.equal(await page.getByRole('radio', { name: 'Alpha', exact: true }).getAttribute('aria-checked'), 'true')
    assert.equal(await page.evaluate(() => document.activeElement?.getAttribute('aria-label')), 'Fixture dropdown')
    await dropdown.click(); await page.keyboard.press('Escape')
    assert.equal(await page.getByRole('dialog').count(), 1)
    const menu = page.getByRole('button', { name: 'Fixture menu', exact: true })
    await menu.focus(); await page.keyboard.press('ArrowDown'); await page.keyboard.press('End')
    assert.equal(await page.evaluate(() => document.activeElement?.textContent?.trim()), 'Last action')
    await page.keyboard.press('Escape')
    assert.equal(await page.evaluate(() => document.activeElement?.getAttribute('aria-label')), 'Fixture menu')
    await page.keyboard.press('Escape')
  })
  await check('Play is visible on keyboard focus and touch', async () => {
    const play = page.locator('#library').getByRole('button', { name: 'Play Fixture game', exact: true })
    await play.focus()
    await page.waitForFunction(() => {
      const el = [...document.querySelectorAll('#library button')].find(b => b.getAttribute('aria-label') === 'Play Fixture game')
      return el && getComputedStyle(el).opacity === '1'
    })
    const context = await browser.newContext({ hasTouch: true, isMobile: true, viewport: { width: 390, height: 844 } })
    const touch = await context.newPage(); await touch.goto(`${base}/test/ui.html`)
    const target = touch.locator('#library').getByRole('button', { name: 'Play Fixture game', exact: true })
    await target.waitFor()
    assert.equal(await target.evaluate(el => getComputedStyle(el).opacity), '1')
    await touch.waitForFunction(() => {
      const el = document.querySelector('[aria-label="Play Fixture game"]')
      const box = el?.getBoundingClientRect()
      return box && box.width >= 44 && box.height >= 44
    })
    const box = await target.boundingBox(); assert(box && box.width >= 44 && box.height >= 44)
    await context.close()
  })
  await check('failed search offers Retry instead of saying no games matched', async () => {
    let failed = true
    await page.route('**/api/games/search?**', route => route.fulfill({ status: failed ? 503 : 200, contentType: 'application/json', body: JSON.stringify(failed ? { error: 'Search unavailable' } : { results: [] }) }))
    await page.locator('#search').click()
    await page.getByPlaceholder(/Search|search/).fill('Fixture title')
    await expectText('[role="dialog"]', 'Try again')
    failed = false
    await page.getByRole('dialog').getByRole('button', { name: 'Retry', exact: true }).click()
    await expectText('[role="dialog"]', 'Nothing on kryo.to by that name')
    await page.keyboard.press('Escape')
  })
  await check('native and web bridges never load preview fixtures or start simulation timers', async () => {
    for (const mode of ['native', 'web', 'preview']) {
      const probe = await browser.newPage()
      const requests = []
      probe.on('request', r => { if (r.url().includes('/src/lib/preview.ts')) requests.push(r.url()) })
      await probe.goto(`${base}/test/bridge.html?mode=${mode}`)
      await probe.waitForFunction(() => document.querySelector('#result')?.textContent === 'Ready')
      const state = await probe.evaluate(() => window.bridgeResult)
      assert.equal(state.intervals, mode === 'preview' ? 1 : 0)
      assert.equal(state.cleared, mode === 'preview' ? 1 : 0)
      assert.equal(requests.length, mode === 'preview' ? 1 : 0)
      if (mode !== 'preview') assert.equal(state.result, mode)
      await probe.close()
    }
  })
  await check('settings recovery precedes normal controls and retains privacy choices on failure', async () => {
    const recovery = await browser.newPage({ viewport: { width: 1100, height: 800 } })
    recovery.on('pageerror', e => failures.push(e.message))
    await recovery.goto(`${base}/test/recovery.html`)
    const button = recovery.getByRole('button', { name: 'Use defaults', exact: true })
    await button.waitFor()
    assert.equal(await recovery.getByRole('button', { name: 'Quit Kryoto', exact: true }).count(), 1)
    await button.click()
    await recovery.getByText('Synthetic permission refusal. Original kept.', { exact: true }).waitFor()
    assert.equal(await button.count(), 1)
    await button.click()
    await recovery.waitForFunction(() => window.recoveryFixture.saved?.recoveryError === null)
    const saved = await recovery.evaluate(() => window.recoveryFixture.saved)
    assert.equal(saved.sendReports, false); assert.equal(saved.sharePlaytime, false)
    await recovery.waitForFunction(() => ![...document.querySelectorAll('button')].some(b => b.textContent === 'Use defaults'))
    await recovery.close()
  })
  assert.deepEqual(failures, [])
  console.log('All Desktop UI regressions passed')
} finally { await browser.close() }
